name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN 

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag chshahid/cicd-test:latest
        
      - name: Docker Push
        run: docker push chshahid/cicd-test:latest
        if: success()  # Run this step only if the build is successful
